/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TutorialLazyImport = createFileRoute('/tutorial')()
const SlidesLazyImport = createFileRoute('/slides')()
const SelectLazyImport = createFileRoute('/select')()
const ProfileLazyImport = createFileRoute('/profile')()
const KomutatifLazyImport = createFileRoute('/komutatif')()
const EvaluasiLazyImport = createFileRoute('/evaluasi')()
const DistributifLazyImport = createFileRoute('/distributif')()
const AsosiatifLazyImport = createFileRoute('/asosiatif')()
const AsalLazyImport = createFileRoute('/asal')()
const AhliLazyImport = createFileRoute('/ahli')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TutorialLazyRoute = TutorialLazyImport.update({
  path: '/tutorial',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/tutorial.lazy').then((d) => d.Route))

const SlidesLazyRoute = SlidesLazyImport.update({
  path: '/slides',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/slides.lazy').then((d) => d.Route))

const SelectLazyRoute = SelectLazyImport.update({
  path: '/select',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/select.lazy').then((d) => d.Route))

const ProfileLazyRoute = ProfileLazyImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const KomutatifLazyRoute = KomutatifLazyImport.update({
  path: '/komutatif',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/komutatif.lazy').then((d) => d.Route))

const EvaluasiLazyRoute = EvaluasiLazyImport.update({
  path: '/evaluasi',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/evaluasi.lazy').then((d) => d.Route))

const DistributifLazyRoute = DistributifLazyImport.update({
  path: '/distributif',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/distributif.lazy').then((d) => d.Route))

const AsosiatifLazyRoute = AsosiatifLazyImport.update({
  path: '/asosiatif',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/asosiatif.lazy').then((d) => d.Route))

const AsalLazyRoute = AsalLazyImport.update({
  path: '/asal',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/asal.lazy').then((d) => d.Route))

const AhliLazyRoute = AhliLazyImport.update({
  path: '/ahli',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/ahli.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/ahli': {
      preLoaderRoute: typeof AhliLazyImport
      parentRoute: typeof rootRoute
    }
    '/asal': {
      preLoaderRoute: typeof AsalLazyImport
      parentRoute: typeof rootRoute
    }
    '/asosiatif': {
      preLoaderRoute: typeof AsosiatifLazyImport
      parentRoute: typeof rootRoute
    }
    '/distributif': {
      preLoaderRoute: typeof DistributifLazyImport
      parentRoute: typeof rootRoute
    }
    '/evaluasi': {
      preLoaderRoute: typeof EvaluasiLazyImport
      parentRoute: typeof rootRoute
    }
    '/komutatif': {
      preLoaderRoute: typeof KomutatifLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/select': {
      preLoaderRoute: typeof SelectLazyImport
      parentRoute: typeof rootRoute
    }
    '/slides': {
      preLoaderRoute: typeof SlidesLazyImport
      parentRoute: typeof rootRoute
    }
    '/tutorial': {
      preLoaderRoute: typeof TutorialLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AhliLazyRoute,
  AsalLazyRoute,
  AsosiatifLazyRoute,
  DistributifLazyRoute,
  EvaluasiLazyRoute,
  KomutatifLazyRoute,
  ProfileLazyRoute,
  SelectLazyRoute,
  SlidesLazyRoute,
  TutorialLazyRoute,
])

/* prettier-ignore-end */
