/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SelectLazyImport = createFileRoute('/select')()
const ProfileLazyImport = createFileRoute('/profile')()
const AsalLazyImport = createFileRoute('/asal')()
const AhliLazyImport = createFileRoute('/ahli')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SelectLazyRoute = SelectLazyImport.update({
  path: '/select',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/select.lazy').then((d) => d.Route))

const ProfileLazyRoute = ProfileLazyImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/profile.lazy').then((d) => d.Route))

const AsalLazyRoute = AsalLazyImport.update({
  path: '/asal',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/asal.lazy').then((d) => d.Route))

const AhliLazyRoute = AhliLazyImport.update({
  path: '/ahli',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/ahli.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/ahli': {
      preLoaderRoute: typeof AhliLazyImport
      parentRoute: typeof rootRoute
    }
    '/asal': {
      preLoaderRoute: typeof AsalLazyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      preLoaderRoute: typeof ProfileLazyImport
      parentRoute: typeof rootRoute
    }
    '/select': {
      preLoaderRoute: typeof SelectLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AhliLazyRoute,
  AsalLazyRoute,
  ProfileLazyRoute,
  SelectLazyRoute,
])

/* prettier-ignore-end */
